version: '3'
services:
    app:
        container_name: zadarma_app
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./public:/var/www/html/public
            - ./src:/var/www/html/src
        depends_on:
            - db
        networks:
            - app-network

    db:
        image: mariadb
        container_name: zadarma_db
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: zadarma
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - .docker/mysql/data:/var/lib/mysql
        user: mysql
        networks:
            - app-network

    adminer:
        image: adminer
        restart: always
        environment:
            ADMINER_DESIGN: haeckel
        networks:
            - app-network
        ports:
            - "8081:8080"
        links:
            - db
networks:
    app-network:
        driver: bridge
